language: scala

scala:
  - 2.13.1

jdk:
  - openjdk11

branches:
  only:
    - master

after_script:
  - sbt "show test:fullClasspath"
  - echo $JAVA_OPTS

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier
