language: scala

scala:
  - 2.13.1

jdk:
  - openjdk11

env:
  global:
    JAVA_OPTS=-Xmx512m

before_script:
  - sbt "show test:fullClasspath"
  - echo $JAVA_OPTS

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier
